package org.objectweb.proactive.core.group;

import org.objectweb.proactive.annotation.PublicAPI;


/**
 * Exception thrown if there is an error when trying to decide where allocate the method call generated by a group.
 *
 * @author The ProActive Team
 *
 */
@PublicAPI
public class AllocationException extends RuntimeException {

    public AllocationException() {
        super();
    }

    public AllocationException(String message, Throwable cause) {
        super(message, cause);
    }

    public AllocationException(String message) {
        super(message);
    }

    public AllocationException(Throwable cause) {
        super(cause);
    }

}
